# Generated by Django 4.2.3 on 2023-07-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='geder',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
