# Generated by Django 4.2.3 on 2023-07-27 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 7, 26, 22, 2, 31, 954902)),
        ),
    ]
