# Generated by Django 4.2.3 on 2023-07-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_item_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='categ',
            field=models.ManyToManyField(to='erp.category'),
        ),
    ]
